/*
 * erica_people_detector.h
 *
 *  Created on: Jan 23, 2019
 *      Author: jay
 */

#ifndef HEROEHS_ERICA_ALICE_HEROEHS_ERICA_PERCEPTION_ERICA_PEOPLE_DETECTOR_INCLUDE_ERICA_PEOPLE_DETECTOR_ERICA_PEOPLE_DETECTOR_H_
#define HEROEHS_ERICA_ALICE_HEROEHS_ERICA_PERCEPTION_ERICA_PEOPLE_DETECTOR_INCLUDE_ERICA_PEOPLE_DETECTOR_ERICA_PEOPLE_DETECTOR_H_





#endif /* HEROEHS_ERICA_ALICE_HEROEHS_ERICA_PERCEPTION_ERICA_PEOPLE_DETECTOR_INCLUDE_ERICA_PEOPLE_DETECTOR_ERICA_PEOPLE_DETECTOR_H_ */
